<a href="https://colab.research.google.com/github/NourhanDeifSayed/Mahcien-Learning-from-scratch/blob/main/KNN_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 #our first step import impoertant packedges
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

from collections import Counter

from sklearn.metrics import accuracy_score
!pip install seaborn
import seaborn as sns

from sklearn.metrics import accuracy_score



In [ ]:
iris=load_iris()
data=iris.data
target=iris.target
X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.2)
print(X_train.shape)

(120, 4)


In [ ]:

X_train = np.asarray(X_train)
y_train = np.asarray(y_train)

X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

In [ ]:
def Euclidean_distance(X_train, X_test):
    distances = []
    for row in range(len(X_train)):
        current_train_point = X_train[row]
        if isinstance(current_train_point, np.ndarray):
            current_distance = np.sqrt(np.sum((current_train_point - X_test) ** 2))
        else:
            current_distance = np.abs(current_train_point - X_test)
        distances.append(current_distance)
    return np.array(distances)



In [ ]:
def Neighrest_neighbors(distance_point, k_val):
    df_distance = pd.DataFrame({'dist': distance_point, 'index': range(len(distance_point))})


    df_nearest = df_distance.sort_values(by='dist')


    df_nearest = df_nearest.head(k_val)

    return df_nearest


In [ ]:
from collections import Counter
from itertools import count
def voting(df_nearest,y_train):
  counter_vote=Counter(y_train[df_nearest.index])
  y_perd=counter_vote.most_common()[0][0]
  return y_perd

In [ ]:
def KNN(X_train, y_train, X_test, K_va):
    y_pred = []
    for test in X_test:
        distance_point = Euclidean_distance(X_train, test)
        nearest_point = Neighrest_neighbors(distance_point, K_va)
        y_perd_point = voting(nearest_point, y_train)
        y_pred.append(y_perd_point)
    return y_pred



In [ ]:
print("X train before Normalization")
print(X_train[0:7])
print("\nX train after Normalization")
print(normalized_X_train[0:7])

X train before Normalization
[[6.3 2.8 5.1 1.5]
 [5.2 4.1 1.5 0.1]
 [6.  3.  4.8 1.8]
 [5.1 3.7 1.5 0.4]
 [6.1 2.9 4.7 1.4]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]]

X train after Normalization
[[0.61111111 0.45454545 0.81355932 0.875     ]
 [0.36111111 0.45454545 0.59322034 0.58333333]
 [0.16666667 0.5        0.08474576 0.04166667]
 [0.25       0.63636364 0.06779661 0.04166667]
 [0.36111111 0.40909091 0.44067797 0.5       ]
 [0.41666667 0.31818182 0.69491525 0.75      ]
 [0.44444444 0.54545455 0.6440678  0.70833333]]


In [ ]:
k_val=3
from sklearn.preprocessing import MinMaxScaler


prediction=KNN(X_test,y_train,X_train,k_val)
print(prediction)


[1, 0, 1, 0, 0, 2, 1, 1, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 1, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 2, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 0, 1, 0]


In [ ]:
k_val=3
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
normalized_X_train = scaler.transform(X_train)

normalized_X_test = scaler.transform(X_test)

prediction=KNN(normalized_X_test,y_train,normalized_X_train,k_val)
print(prediction)

acc = np.sum(np.array(KNN(normalized_X_train, y_train, normalized_X_test, k_val)) == y_test) / len(y_test)
print("Accuracy:", acc*100)



[1, 0, 1, 0, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 1, 0, 1, 2, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 2, 2, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 1, 1, 1, 1, 0]
Accuracy: 100.0


In [ ]:
k_val=5
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
normalized_X_train = scaler.transform(X_train)

normalized_X_test = scaler.transform(X_test)

prediction=KNN(normalized_X_test,y_train,normalized_X_train,k_val)
print(prediction)
acc = np.sum(np.array(KNN(normalized_X_train, y_train, normalized_X_test, k_val)) == y_test) / len(y_test)
print("Accuracy:", acc*100)


[1, 0, 1, 0, 2, 2, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 1, 2, 2, 0, 0, 0, 1, 2, 2, 0, 1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2, 2, 2, 0, 0, 1, 2, 1, 2, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 2, 1, 2, 1, 0, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0]
Accuracy: 100.0


In [ ]:
k_val=7
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
normalized_X_train = scaler.transform(X_train)

normalized_X_test = scaler.transform(X_test)

prediction=KNN(normalized_X_test,y_train,normalized_X_train,k_val)
print(prediction)

acc = np.sum(np.array(KNN(normalized_X_train, y_train, normalized_X_test, k_val)) == y_test) / len(y_test)
print("Accuracy:", acc*100)


[1, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 2, 2, 2, 0, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 0, 2, 1, 1, 0, 2, 2, 1, 2, 0, 1, 2, 1, 0, 1, 2, 2, 0, 0, 2, 2, 0, 1, 2, 2, 0, 0, 0, 1, 2, 2, 0, 2, 2, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 1, 1, 2, 0, 1, 0, 2, 0, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 0, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0]
Accuracy: 100.0


In [ ]:
#the output here is same becuase the meaugerments of all features are equvalent

In [ ]:


knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(normalized_X_train, y_train)

y_pred = knn.predict(normalized_X_test)

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc*100)

Accuracy: 100.0
